
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showInputDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kevin
 */
public class frmMessage extends javax.swing.JFrame {

    /**
     * Creates new form frmMessage
     */
    public frmMessage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenssagem = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenssagem.setText("Menssagem");
        btnMenssagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenssagemActionPerformed(evt);
            }
        });

        btnInput.setText("Input Text");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnMenssagem)
                .addGap(39, 39, 39)
                .addComponent(btnInput)
                .addGap(35, 35, 35)
                .addComponent(btnConfirm)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenssagem)
                    .addComponent(btnInput)
                    .addComponent(btnConfirm))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenssagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenssagemActionPerformed
        JOptionPane.showMessageDialog(null, "msg mais curta");
        JOptionPane.showMessageDialog(null, "ERROR", "Título da caixa", JOptionPane.ERROR_MESSAGE);
        JOptionPane.showMessageDialog(null, "INFORMATION", "Título da caixa", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "WARNING", "Título da caixa", JOptionPane.WARNING_MESSAGE);
        JOptionPane.showMessageDialog(null, "QUESTION", "Título da caixa", JOptionPane.QUESTION_MESSAGE);
        JOptionPane.showMessageDialog(null, "PLAIN", "Título da caixa", JOptionPane.PLAIN_MESSAGE); //sem imagem
    }//GEN-LAST:event_btnMenssagemActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        String resultado;
        resultado = showInputDialog(null, "Quantos anos você tem?","VOLTAÇÂO",JOptionPane.QUESTION_MESSAGE);
        System.out.println(resultado);
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
 int res = JOptionPane.showConfirmDialog(null, "Do you like bacon?", "PESQUISA", JOptionPane.YES_NO_OPTION);
        if(res == 0) {
           System.out.println("Bacon é vida");
        } else if (res == 1) {
          System.out.println("Vá comprar e experimentar bacon");
        } else {
          System.out.println("Após cancelar, compre e coma bacon");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnMenssagem;
    // End of variables declaration//GEN-END:variables
}
